---
# This is the workday sensor. This binary sensor tells me if it is
# a workday today. It takes into account holidays as well!
#
# https://www.home-assistant.io/integrations/workday/
#
platform: workday
name: workday
country: US
province: MO
workdays:
  - mon
  - tue
  - wed
  - thu
  - fri
